//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPhotos
{
    using System;
    using System.Collections.Generic;
    
    public partial class CharValue
    {
        public int Id { get; set; }
        public string Value { get; set; }
        public int CharacteristicId { get; set; }
    
        public virtual Media Media { get; set; }
        public virtual Characteristic Characteristic { get; set; }
    }
}
